services:
  db:
    image: postgres:16-alpine
    container_name: reservas-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - reservas-net

  backend:
    build:
      context: ./backend
    container_name: reservas-backend
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
      PYTHONUNBUFFERED: "1"
      FLASK_ENV: development
      FLASK_DEBUG: "1"
      FLASK_APP: app:create_app
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"
    volumes:
      - ./backend:/app
    command: flask run --host=0.0.0.0 --port=8000 --debug
    networks:
      - reservas-net


  frontend:
    build:
      context: ./frontend
    container_name: reservas-frontend
    env_file:
      - .env
    environment:
      VITE_API_URL: ${VITE_API_URL}
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    expose:
      - "5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    networks:
      - reservas-net



  nginx:
    image: nginx:1.27-alpine
    container_name: reservas-nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - reservas-net

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: reservas-pgadmin
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - reservas-net

volumes:
  pgdata:
  pgadmin_data:
  frontend_node_modules:

networks:
  reservas-net:
    driver: bridge
